CREATE SEQUENCE seq_usuario AS NUMERIC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pessoa AS NUMERIC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_movimento AS NUMERIC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_produto AS NUMERIC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_endereco AS NUMERIC START WITH 1 INCREMENT BY 1;